// Copyright (c) 2026 Charles K. Johnson
// SPDX-License-Identifier: BSL-1.1

import 'fastify';

declare module 'fastify' {
  interface FastifyRequest {
    /**
     * ULID generated by trace middleware on every request.
     * Set before gatewaySecretHook fires — present on all requests
     * including rejected ones. Never undefined after traceHook runs.
     */
    traceId: string;

    /**
     * Clerk user sub extracted from Authorization Bearer JWT by
     * audit middleware. Null for unauthenticated requests (e.g.
     * /health) and requests rejected before auth resolves.
     */
    callerIdentity: string | null;

    /**
     * Request start timestamp in milliseconds (Date.now()).
     * Set by auditStartHook on every request for duration_ms
     * calculation in auditHook.
     */
    startMs: number;
  }
}
